### ISSUE TITLE
crash under sway, but not weston

### ISSUE THREAD

**Issue by boogerlad** [michaelforney/st#6]
Looks like the default makefile has the -g parameter, so debug symbols are included. Is this correct? I hope this is more useful.

```
[root@localhost st]# WAYLAND_DEBUG=1 gdb st
GNU gdb (GDB) 7.12
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from st...done.
(gdb) run
Starting program: /root/st/st 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[739345.719]  -> wl_display@1.get_registry(new id wl_registry@2)
[739345.778]  -> wl_display@1.get_registry(new id wl_registry@3)
[739345.804]  -> wl_display@1.sync(new id wl_callback@4)
[739345.942] wl_display@1.delete_id(4)
[739345.998] wl_registry@3.global(1, "wl_shm", 1)
[739346.026] wl_registry@3.global(2, "wl_compositor", 3)
[739346.044] wl_registry@3.global(3, "wl_subcompositor", 1)
[739346.063] wl_registry@3.global(4, "wl_data_device_manager", 2)
[739346.083] wl_registry@3.global(5, "wl_seat", 4)
[739346.119] wl_registry@3.global(6, "wl_shell", 1)
[739346.140] wl_registry@3.global(7, "zxdg_shell_v6", 1)
[739346.159] wl_registry@3.global(8, "desktop_shell", 3)
[739346.179] wl_registry@3.global(9, "lock", 1)
[739346.197] wl_registry@3.global(10, "wl_output", 2)
[739346.217] wl_registry@3.global(11, "wl_drm", 2)
[739346.239]  -> wl_registry@3.bind(11, "wl_drm", 2, new id [unknown]@5)
[739346.267] wl_callback@4.done(20609)
[739346.280]  -> wl_display@1.sync(new id wl_callback@4)
[739346.332] wl_display@1.delete_id(4)
[739346.343] wl_drm@5.device("/dev/dri/card0")
[739346.380]  -> wl_drm@5.authenticate(2)
[739346.389] wl_drm@5.format(875713089)
[739346.401] wl_drm@5.format(875713112)
[739346.409] wl_drm@5.format(909199186)
[739346.419] wl_drm@5.format(961959257)
[739346.428] wl_drm@5.format(825316697)
[739346.440] wl_drm@5.format(842093913)
[739346.449] wl_drm@5.format(909202777)
[739346.456] wl_drm@5.format(875713881)
[739346.463] wl_drm@5.format(842094158)
[739346.469] wl_drm@5.format(909203022)
[739346.476] wl_drm@5.format(1448695129)
[739346.483] wl_drm@5.capabilities(1)
[739346.491] wl_callback@4.done(20609)
[739346.498]  -> wl_display@1.sync(new id wl_callback@4)
[739346.536] wl_display@1.delete_id(4)
[739346.546] wl_drm@5.authenticated()
[739346.551] wl_callback@4.done(20609)
# find_driver: Trying DRM driver `intel'
[739346.660]  -> wl_display@1.sync(new id wl_callback@4)
[739346.673] wl_registry@2.global(1, "wl_shm", 1)
[739346.691]  -> wl_registry@2.bind(1, "wl_shm", 1, new id [unknown]@6)
[739346.717] wl_registry@2.global(2, "wl_compositor", 3)
[739346.733]  -> wl_registry@2.bind(2, "wl_compositor", 3, new id [unknown]@7)
[739346.753] wl_registry@2.global(3, "wl_subcompositor", 1)
[739346.770] wl_registry@2.global(4, "wl_data_device_manager", 2)
[739346.789]  -> wl_registry@2.bind(4, "wl_data_device_manager", 1, new id [unknown]@8)
[739346.813] wl_registry@2.global(5, "wl_seat", 4)
[739346.831]  -> wl_registry@2.bind(5, "wl_seat", 4, new id [unknown]@9)
[739346.856] wl_registry@2.global(6, "wl_shell", 1)
[739346.874] wl_registry@2.global(7, "zxdg_shell_v6", 1)
[739346.922] wl_registry@2.global(8, "desktop_shell", 3)
[739346.949] wl_registry@2.global(9, "lock", 1)
[739346.988] wl_registry@2.global(10, "wl_output", 2)
[739347.019]  -> wl_registry@2.bind(10, "wl_output", 2, new id [unknown]@10)
[739347.056] wl_registry@2.global(11, "wl_drm", 2)
[739351.894] wl_display@1.delete_id(4)
[739351.942] wl_callback@4.done(20609)
[739351.964]  -> wl_seat@9.get_keyboard(new id wl_keyboard@4)
[739351.977]  -> wl_seat@9.get_pointer(new id wl_pointer@11)
[739351.987]  -> wl_data_device_manager@8.get_data_device(new id wl_data_device@12, wl_seat@9)
# wld_font_open_pattern: Loading font file: /usr/share/fonts/TTF/DejaVuSans.ttf
# wld_font_open_pattern: Loading font file: /usr/share/fonts/TTF/DejaVuSans-Oblique.ttf
# wld_font_open_pattern: Loading font file: /usr/share/fonts/TTF/DejaVuSans-BoldOblique.ttf
# wld_font_open_pattern: Loading font file: /usr/share/fonts/TTF/DejaVuSans-Bold.ttf
[739371.215]  -> wl_shm@6.create_pool(new id wl_shm_pool@13, fd 6, 4096)
[739371.532]  -> wl_shm_pool@13.resize(12288)
[739371.679]  -> wl_shm_pool@13.resize(28672)
[739371.892]  -> wl_shm_pool@13.resize(61440)
[739372.242]  -> wl_shm_pool@13.resize(126976)
[739374.442]  -> wl_shm_pool@13.resize(258048)
[739374.588]  -> wl_shm_pool@13.resize(520192)
[739376.575]  -> wl_shm_pool@13.resize(1044480)
[739380.052]  -> wl_shm_pool@13.resize(2093056)
[739404.413]  -> wl_compositor@7.create_surface(new id wl_surface@14)
[739404.465]  -> wl_compositor@7.create_surface(new id wl_surface@15)

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7124396 in wl_proxy_marshal_constructor () from /usr/lib/libwayland-client.so.0
(gdb) bt
#0  0x00007ffff7124396 in wl_proxy_marshal_constructor () from /usr/lib/libwayland-client.so.0
#1  0x000000000040324a in xdg_shell_get_xdg_surface (surface=<optimized out>, xdg_shell=<optimized out>)
    at xdg-shell-client-protocol.h:359
#2  wlinit () at st.c:3247
#3  main (argc=0, argv=<optimized out>) at st.c:4353

```

**Comment by boogerlad** [comment]
Just tested st@8c99915 and your latest patch in oasis, same problem. Are you able to reproduce with sway? If you're not interested in fixing this, any pointers?

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7124396 in wl_proxy_marshal_constructor () from /usr/lib/libwayland-client.so.0
(gdb) bt
#0  0x00007ffff7124396 in wl_proxy_marshal_constructor () from /usr/lib/libwayland-client.so.0
#1  0x00000000004034b5 in xdg_shell_get_xdg_surface (surface=<optimized out>, xdg_shell=<optimized out>)
    at xdg-shell-unstable-v5-client-protocol.h:421
#2  wlinit () at st.c:3394
#3  main (argc=0, argv=<optimized out>) at st.c:4537

```

**Comment by michaelforney** [comment]
It looks like sway only implements xdg-shell-v6 (which is fairly new), while this st port currently only supports v5.

So, we never see a shell global, and wl.shell is left at NULL. I seem to have missed a NULL check after the first roundtrip in wlinit, causing a crash later on when we try to use wl.shell. Probably if you build st without optimizations, the gcc backtrace will make this clear.

You can try to port to v6 and send a pull request. I'd probably put it in a separate branch for now until I have time to support v6 in swc.

**Comment by etherealvisage** [comment]
I just created a pull request that changes st to use xdg v6. @boogerlad, if you give #8 a try and report back if it works for you, that would be great.
